Repository echoboomer/incident-bot, pull requests merged in 2022-12, with the labels that each got.

#47 Update docs, rename manifests
  .gitignore
  deploy/kustomize/incident-bot/base/deployment.yaml
  deploy/kustomize/incident-bot/base/hpa.yaml
  deploy/kustomize/incident-bot/base/ingress.yaml
  deploy/kustomize/incident-bot/base/kustomization.yaml
  deploy/kustomize/incident-bot/base/namespace.yaml
  deploy/kustomize/incident-bot/base/pdb.yaml
  deploy/kustomize/incident-bot/base/service.yaml
  deploy/kustomize/incident-bot/overlays/development/.env
  deploy/kustomize/incident-bot/overlays/development/kustomization.yaml
  docs/source/setup.rst
Labels: documentation, enhancement

#46 Minor fixes
  backend/bot/confluence/rca.py
  backend/bot/incident/incident.py
  backend/config.py
  backend/tests/test_incident.py
  requirements.txt
Labels: bug

#51 Remove wrong req file, bump Py version + packages
  Dockerfile
  backend/.python-version
  backend/alembic/env.py
  backend/bot/api/flask.py
  backend/bot/api/routes/incident.py
  backend/bot/api/routes/pager.py
  backend/bot/api/routes/postmortem.py
  backend/bot/api/routes/setting.py
  backend/bot/api/routes/user.py
  backend/bot/audit/log.py
  backend/bot/confluence/rca.py
  backend/bot/confluence/template.py
  backend/bot/external/epi.py
  backend/bot/incident/actions.py
  backend/bot/incident/incident.py
  backend/bot/models/incident.py
  backend/bot/models/pager.py
  backend/bot/models/user.py
  backend/bot/pagerduty/api.py
  backend/bot/scheduler/scheduler.py
  backend/bot/shared/tools.py
  backend/bot/slack/client.py
  backend/bot/slack/handler.py
  backend/bot/slack/incident_logging.py
  backend/bot/slack/messages.py
  backend/bot/slack/modals.py
  backend/bot/startup/tasks.py
  backend/bot/statuspage/actions.py
  backend/bot/statuspage/slack.py
  backend/config.py
  backend/main.py
  backend/pyproject.toml
  backend/requirements.txt
  backend/tests/mock_web_api_server.py
  backend/tests/test_app.py
  backend/tests/test_incident.py
  requirements.txt
Labels: enhancement

#61 Various improvements, remove Zoom specificity.
  .github/workflows/tests.yml
  Dockerfile
  Makefile
  backend/.python-version
  backend/Makefile
  backend/bot/incident/incident.py
  backend/bot/settings/im.py
  backend/bot/slack/handler.py
  backend/config.py
  backend/requirements.txt
  backend/templates/slack/incident_digest_notification.json
  backend/templates/slack/incident_digest_notification_update.json
  backend/tests/test_incident.py
  docs/source/features.rst
  pytest.ini
  version
Labels: bug, enhancement
